project_id = "mlqnpewuttnnrjyjoaxk"

[functions.sensor-data]
verify_jwt = false

[functions.plant-advisor]
verify_jwt = false

[functions.plant-health-diagnosis]
verify_jwt = false

[functions.send-alert-email]
verify_jwt = false

[functions.yield-prediction]
verify_jwt = false

[functions.weather-forecast]
verify_jwt = false
